<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-A64RUOI" name="il.co.topq.difido.DifidoReporterTestsPart1" tests="28" failures="0" timestamp="13 May 2017 21:58:28 GMT" time="3.113" errors="4">
  <testcase name="parallelTest" time="0.012" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.005" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="testFailOnBeforeMethod" time="0.008" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- testFailOnBeforeMethod -->
  <testcase name="anotherRandomTest" time="0.243" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.014" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="testWithNoParameters" time="0.016" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="simpleReportCall0" time="1.015" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.006" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="testWithFailure" time="0.004" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <error type="java.lang.Exception" message="This is my failure">
      <![CDATA[java.lang.Exception: This is my failure
	at il.co.topq.difido.DifidoReporterTestsPart1.testWithFailure(DifidoReporterTestsPart1.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testWithFailure -->
  <testcase name="parallelTest" time="0.010" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.004" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.010" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.011" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.007" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.003" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="anotherRandomTest" time="0.003" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="testWithInsufficientMandatoryParams" time="0.005" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="setUp" time="0.457" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <error type="java.lang.Exception" message="My failure at before method">
      <![CDATA[java.lang.Exception: My failure at before method
	at il.co.topq.difido.DifidoReporterTestsPart1.setUp(DifidoReporterTestsPart1.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="testWithFailure" time="0.239" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <error type="java.lang.Exception" message="This is my failure">
      <![CDATA[java.lang.Exception: This is my failure
	at il.co.topq.difido.DifidoReporterTestsPart1.testWithFailure(DifidoReporterTestsPart1.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testWithFailure -->
  <testcase name="simpleReportCall0" time="1.003" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="testWithNoParameters" time="0.000" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- testWithNoParameters -->
  <testcase name="setUp" time="0.008" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <error type="java.lang.Exception" message="My failure at before method">
      <![CDATA[java.lang.Exception: My failure at before method
	at il.co.topq.difido.DifidoReporterTestsPart1.setUp(DifidoReporterTestsPart1.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="testWithInsufficientMandatoryParams" time="0.012" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.001" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="testFailOnBeforeMethod" time="0.001" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- testFailOnBeforeMethod -->
  <testcase name="parallelTest" time="0.009" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.001" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.006" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
</testsuite> <!-- il.co.topq.difido.DifidoReporterTestsPart1 -->
