<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-A64RUOI" ignored="1" name="First Wave" tests="6" failures="1" timestamp="13 May 2017 21:58:24 GMT" time="1.36" errors="0">
  <testcase name="@BeforeMethod setUp" time="0.228" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <failure type="java.lang.Exception" message="My failure at before method">
      <![CDATA[java.lang.Exception: My failure at before method
	at il.co.topq.difido.DifidoReporterTestsPart1.setUp(DifidoReporterTestsPart1.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="failOnBeforeMethod  null" time="0.001" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- failOnBeforeMethod  null -->
  <testcase name="arg0  null" time="0.012" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="arg0  arg1" time="0.014" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="arg0  null" time="0.011" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <failure type="java.lang.Exception" message="This is my failure">
      <![CDATA[java.lang.Exception: This is my failure
	at il.co.topq.difido.DifidoReporterTestsPart1.testWithFailure(DifidoReporterTestsPart1.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- arg0  null -->
  <testcase name="null  null" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <skipped/>
  </testcase> <!-- null  null -->
  <testcase name="arg0  arg1" time="1.008" classname="il.co.topq.difido.DifidoReporterTestsPart1"/>
  <testcase name="parallelTest" time="0.0" classname="il.co.topq.difido.DifidoReporterTestsPart1">
    <ignored/>
  </testcase> <!-- parallelTest -->
</testsuite> <!-- First Wave -->
